name: "Unit test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Execute test
      run: sh ./.github/scripts/testCov.sh

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.txt
        fail_ci_if_error: true
        verbose: true
